#!/usr/bin/env perl
use strict;
use warnings;

use Algorithm::Combinatorics qw(variations_with_repetition);

my $k = shift || 3;                  # How many objects?
my @range = @ARGV ? @ARGV : 1 .. $k; # The range of possible values

my $v = variations_with_repetition(\@range, $k);

my $n = @$v + 1;
my $i = 0;

while (my $x = $v->next) {
    printf "%*d. %s\n", $n, ++$i, join(' ', @$x);
}
