#!/usr/bin/env perl
use strict;
use warnings;

use Math::Big qw( pi euler );
use Math::Prime::XS qw( primes is_prime );

my $digits = shift || 100;
my $span   = shift || 1;
my $type   = shift || 'pi';

my $number;
if ( $type =~ /^e/ ) {
    $number = euler( 1, $digits );
}
elsif ( $type =~ /^r/ ) {
    $number = join '', map { int rand 10 } 1 .. $digits;
}
elsif ( $type =~ /^p/ ) {
    my @primes = primes( $digits * $digits );
    $number = join '', @primes;
    $number = substr $number, 0, $digits;
}
else {
    $number = pi($digits);
}

( my $decimal = $number ) =~ s/\A\d\.(.*)\z/$1/;
print "Decimal: $decimal\n";

my ( $position, $prime ) = ( 0, 0 );

while ( $position + $span - 1 < length($decimal) ) {
    my $group = substr $decimal, $position, $span;

    my $flag = '';

    if ( is_prime($group) ) {
        $prime++;
        $flag = ' *';
    }

    printf "%3d. %s%s\n", $position + 1, $group, $flag;

    $position++;
}

printf "For %s groups of %d, there are %d primes out of %d total (%.2f%%).\n",
    $type, $span, $prime, $position, $prime / $position;

__END__
groups <- c( 388,430,362,336,163,119,94,94,95,85,68,65,57,52,44,40,45,35,33 ) # primes
plot( groups, type='l',col='red',main="Primes Seen in Sequence Groups", xlab="Group size", ylab="Primes seen" )

groups <- c( 397,264,158,120,99,83,80,65,59,55,44,49,33,28,26,27,35,19,19 ) # pi
lines( groups, type='l' )

groups <- c( 417,244,195,113,89,91,59,57,42,54,33,34,33,43,21,32,20,30,20 ) # random
lines( groups, type='l',col='blue' )

groups <- c( 424,223,160,132,105,68,57,52,59,40,35,36,33,39,21,24,23,24,17 ) # random
lines( groups, type='l',col='dark_green' )

legend("topright", inset=.05, legend=c("primes","pi","random","random"), col=c("red","black","blue","darkgreen"), lty=1, cex=0.8)
