#!/usr/bin/env perl
use strict;
use warnings;

use Math::Big qw( pi euler );
use Math::Prime::XS qw( is_prime );

my $digits = shift // 100;
my $span   = shift // 1;

#my $num = pi($digits);
my $num = euler( 1, $digits );

( my $decimal = $num ) =~ s/\A\d\.(.*)\z/$1/;
print "$decimal\n";

my $i = 0;

while ( $i + $span - 1 < length($decimal) ) {
    my $group = substr $decimal, $i, $span;

    printf "%3d. %s%s\n", $i, $group, is_prime($group) ? ' *' : '';

    $i++;
}
