#!/usr/bin/perl
use strict;
use warnings;
use Date::Calc qw(Add_Delta_Days);

my ($y,$m,$d) = (1900, 1, 1);

my $n = {};

my $digit_sum = sub {
    my $x = shift;
    my $y = 0;
    $y += $_ for split //, $x;
    return $y;
};

while ($y < 2000) {
    my $i = $digit_sum->("$y$m$d");
#warn"$m/$d/$y\n" if length $i == 1;
    my $j = $digit_sum->($i);
    $n->{"$i/$j"}++;
    ($y, $m, $d) = Add_Delta_Days($y, $m, $d, 1);
}

use Data::Dumper;local$Data::Dumper::Indent=1;local$Data::Dumper::Terse=1;local$Data::Dumper::Sortkeys=1;
warn Dumper(scalar(keys %$n), $n);
