#!/usr/bin/env perl
use strict;
use warnings;

# An enthusiastic friend showed me this book,
# "The Life You Were Born to Live: A Guide to Finding Your Life Purpose"
# ISBN 091581160X by Dan Millman.

my @birthdate = @ARGV ? @ARGV : die "Usage: perl $0 YYYY MM DD\n";

# Perform the magical computations!
my $x = reduce_digits(@birthdate);

if ( length($x) > 1 ) {
    $x = reduce_digits($x);
}

print "Birth number = $x\n";

# Return the sum of the digits of a number.
sub num_sum {
    my $x = shift;
    my $y = 0;
    $y += $_ for split //, $x;
    return $y;
}

sub reduce_digits {
    my @date = @_;

    my @digits;

    # Reduce the date to a single digit.
    for my $x ( @date ) {
        while ( length $x > 1 ) {
            $x = num_sum($x);
        }
        push @digits, $x;
    }

    # Reduce the digits to a single digit.
    my $sum = 0;
    $sum += $_ for @digits;

    return $sum;
}
