#!/usr/bin/env perl
use strict;
use warnings;

# An enthusiastic friend showed me this book,
# "The Life You Were Born to Live: A Guide to Finding Your Life Purpose"
# ISBN 091581160X by Dan Millman.

my $birthdate = shift || die "Usage: perl $0 YYYY/MM/DD\n";

my @digits = split /\//, $birthdate;

# Return the sum of the digits of a number.
my $digit_sum = sub {
    my $x = shift;
    my $y = 0;
    $y += $_ for split //, $x;
    return $y;
};

# Perform the magical computations!
my $x = sum_digits(@digits);

if ( length($x) > 1 ) {
    $x = sum_digits($x);
}

print "$x\n";

sub sum_digits {
    my @args = @_;

    my @digits;

    for my $x ( @args ) {
        while ( length $x > 1 ) {
            $x = $digit_sum->($x);
        }
        push @digits, $x;
    }

    my $sum = 0;
    $sum += $_ for @digits;

    return $sum;
}
