#!/usr/bin/env perl
use strict;
use warnings;

use Math::Big qw( pi );
use Math::Prime::XS qw( is_prime );

my $digits = shift // 100;
my $span   = shift // 1;

my $pi = pi($digits);
( my $decimal = $pi ) =~ s/\A\d\.(.*)\z/$1/;
print "$decimal\n";

my $i = 0;

while ( $i + $span - 1 < length($decimal) ) {
    my $x = substr $decimal, $i, $span;

    printf "%3d. %s%s\n", $i, $x, is_prime($x) ? ' *' : '';

    $i++;
}
