#!/usr/bin/env perl
use strict;
use warnings;

use Data::Dumper;
use Algorithm::Combinatorics qw( variations_with_repetition );
use List::MoreUtils qw( all );

# Player strategies.
my $p1 = {
    1 => [1,1,3],
    2 => [0,0,3],
    3 => [0,2,5],
};
my $p2 = {
    1 => [0,2,2],
    2 => [3,1,4],
    3 => [0,0,3],
};

reduce_game($p2, $p1);
reduce_game($p1, $p2);
reduce_game($p2, $p1);
reduce_game($p1, $p2);
warn Data::Dumper->new([$p1, $p2])->Indent(1)->Terse(1)->Quotekeys(0)->Sortkeys(1)->Dump;

sub reduce_game {
    my ($player, $opponent) = @_;
    #use Data::Dumper;warn Data::Dumper->new([$opponent])->Indent(1)->Terse(1)->Quotekeys(0)->Sortkeys(1)->Dump;

    # Bucket of X|Y strategy pair utilities.
    my $utility = {};

    # Evaluate pairs of strategies.
    my $iter = variations_with_repetition([keys %$player], 2);
    while (my $v = $iter->next) {
        next if $v->[0] eq $v->[1];

        #warn join(', ', @$v), "\n";
        for my $i (0 .. @$v - 1) {
            if (defined $player->{$v->[0]}[$i] && defined $player->{$v->[1]}[$i]) {
                #warn "$i: $player->{$v->[0]}[$i] vs $player->{$v->[1]}[$i]\n";
                if ($player->{$v->[0]}[$i] > $player->{$v->[1]}[$i]) {
                    # Strictly dominant utility
                    push @{ $utility->{join '|', @$v} }, 1;
                }
                elsif ($player->{$v->[0]}[$i] < $player->{$v->[1]}[$i]) {
                    # Strictly dominated utility
                    push @{ $utility->{join '|', @$v} }, -1;
                }
                else {
                    # Equivalent utility
                    push @{ $utility->{join '|', @$v} }, 0;
                }
            }
        }
    }
    #warn Data::Dumper->new([$utility])->Indent(1)->Terse(1)->Quotekeys(0)->Sortkeys(1)->Dump;

    # Remove strictly dominated strategies.
    for my $strat (keys %$utility) {
        if (all { $_ == -1 } @{$utility->{$strat}}) {
            my @dominated = split /\|/, $strat;
            #warn "U:[@{$utility->{$strat}}]\n";
            #warn "D:'$dominated[0]'\n";
            delete $player->{$dominated[0]};
            # Remove the utilities for the deleted opponent strategy.
            for my $u (keys %$opponent) {
                splice @{$opponent->{$u}}, $dominated[0] - 1, 1;
                #warn "u:'@{$opponent->{$u}}'\n";
            }
            last;
        } 
    }
    #warn Data::Dumper->new([$opponent])->Indent(1)->Terse(1)->Quotekeys(0)->Sortkeys(1)->Dump;
}
