#!/usr/bin/env perl
# Print the gaps between primes
use strict;
use warnings;

use Math::Big qw(primes);

my $limit = shift || 100;
my $size  = shift || 1;

my @primes = primes($limit);

my $width = length $primes[-1];

my $position = 0;

while ( $position + $size - 1 < @primes - 1 ) {
    my $prime   = $primes[$position];
    my $greater = $primes[ $position + $size ];

    my $gap = $greater - $prime;

    printf "%*d. %*d - %*d = %*d [%05b]\n",
        $width, $position + 1,
        $width, $greater,
        $width, $prime,
        $width, $gap,
        $gap;

    $position++;
}

