#!/usr/bin/perl
#
# TODO Description
# -- gene@cpan.org
#
use strict;
use warnings;

use Math::Big qw(primes);

# Set the 
my $min = '2';
# Set the upper modulo limit.
my $mod = shift || '20';
# Set the ceiling for primes to consider.
my $max = shift || $mod;

# Get a list of the primes only.
my @primes = map { $_->{value}[0] } primes($max);
print "Primes less than $max is ", scalar(@primes), "\n";

# Set the field widths for output formatting.
my $mwidth = length($mod);
my $pwidth = length($primes[-1]);
my $iwidth = length(@primes);

printf "%*s  %*s\n", $iwidth, '#', $pwidth, 'P';

my $i = 0;
for my $p (@primes) {
    printf '%*d. %*d ', $iwidth, ++$i, $pwidth, $p;
    for my $m ($min .. $mod) {
        my $rem = $p % $m;
        printf '%*d ', $mwidth, $rem;
    }
    print "\n";
}
