#!/usr/bin/env perl
use strict;
use warnings;

use Math::Prime::XS qw(primes);
use List::MoreUtils qw(firstidx);
use Statistics::Frequency;
use Statistics::R;

my $start = shift // 2;
my $limit = shift // 10;
my $stop  = shift // 6;

my @primes = primes($limit);

my $R; # Interface to the R interpreter

for my $mod ( $start .. $stop ) {
    my @sequence = map { $_ % $mod } @primes;

    my $index = firstidx { $_ == $start } @sequence;

    @sequence = @sequence[ $index .. @sequence  - 1 ];
    #use Data::Dumper::Concise;warn Dumper\@sequence;

    my $last;
    my @x;
    my @y;

    for my $p ( 0 .. @sequence - 1 ) {
        if ( defined $last ) {
            #print "[$sequence[$last],$sequence[$p]]\n";
            push @x, $sequence[$last];
            push @y, $sequence[$p];
            $last = $p;
        }
        else {
            $last = $p;
            next;
        }
    }

    my $freq = Statistics::Frequency->new;
    $freq->add_data(@y);
    my %prop = $freq->proportional_frequencies;
    #use Data::Dumper::Concise;warn Dumper\%prop;

    #print join("\n", @x), "\n";
    #print join("\n", @y), "\n";
    #print join("\n", map { $prop{$_} } @y), "\n";

    $R = Statistics::R->new();
    my $file = sprintf '%s-mod-%.*d.png', $0, length($limit) - 1, $mod;
    $R->run( "png(file='$file')" );
    $R->run( 'x <- c(' . join( ',', @x ) . ')' );
    $R->run( 'y <- c(' . join( ',', @y ) . ')' );
    $R->run( 'z <- c(' . join( ',', map { $prop{$_} } @y ) . ')' );
    $R->run( "plot(x, y, pch=21, bg= gray(z), xlab='P', ylab='P+1', main='Successive Primes to $limit Modulo $mod')" );
    $R->run( 'dev.off()' );
}

$R->stop();
