#!/usr/bin/env perl
use strict;
use warnings;

use Math::Prime::XS qw(primes);
use List::MoreUtils qw(firstidx);
use Statistics::Frequency;

my $start = shift // 2;
my $limit = shift // 10;
my $mod   = shift // 6;

my @primes = map { $_ % $mod } primes($limit);

my $index = firstidx { $_ == $start } @primes;

@primes = @primes[ $index .. @primes  - 1 ];
#use Data::Dumper::Concise;warn Dumper\@primes;

my $last;
my @x;
my @y;

for my $p ( 0 .. @primes - 1 ) {
    if ( defined $last ) {
#        warn "[$primes[$last],$primes[$p]]\n";
        push @x, $primes[$last];
        push @y, $primes[$p];
        $last = $p;
    }
    else {
        $last = $p;
        next;
    }
}

print join(', ', @x), "\n";
print join(', ', @y), "\n";

my $freq = Statistics::Frequency->new;
$freq->add_data(@y);
my %prop = $freq->proportional_frequencies;
#use Data::Dumper::Concise;warn Dumper\%prop;
print join(', ', map { $prop{$_} } @y), "\n";
