#!/usr/bin/perl
#
# This program generates a table of the numbers behind Timothy Butcher's prime
# spiral drawings.  A spiral similar to Ulam's is N=4.  Examples at the bottom.
# -- gene@cpan.org
#
use strict;
use warnings;

# We will be considering the prime numbers.
use Math::Prime::XS qw(is_prime);

# Set the number of columns (or "spokes").
my $spokes = shift
    || die "Usage: perl $0 N M\n\twhere N=spokes (rows), M=rings (columns)\n";
# Set the maximum number of rows (or "rings").
my $max    = shift || $spokes * 20;
# Get the output field width.
my $width  = length $max;

# Output each column.
for my $i (1 .. $max) {
    # Skip evenly divisible numbers.
#    next unless $i % 2;
    # Output a row.
    printf '%*s ', $width, is_prime($i) ? $i : '.';
    # End a row if we are on the last column.
    print "\n" unless $i % $spokes;
}

__END__
# Example 1 with N = 3, M = 21
 .  2  3 
 .  5  . 
 7  .  . 
 . 11  . 
13  .  . 
 . 17  . 
19  .  .

# Example 2 with N = 4, M = 40
 .  2  3  . 
 5  .  7  . 
 .  . 11  . 
13  .  .  . 
17  . 19  . 
 .  . 23  . 
 .  .  .  . 
29  . 31  . 
 .  .  .  . 
37  .  .  .
