#!/usr/bin/perl
#
# This program generates a table of the numbers behind Timothy Butcher's prime
# spiral drawings.  A spiral similar to Ulam's is N=4.
# -- gene@cpan.org
#
use strict;
use warnings;

use Math::Prime::XS qw(is_prime);

# Set the number of columns (or "spokes").
my $spokes = shift || die "Usage: perl $0 N (where N = number of spokes)\n";
# Set the maximum number of rows (or "rings").
my $max    = shift || $spokes * 20;
# Get the output field width.
my $width  = length $max;

# Output each column.
for my $i (1 .. $max) {
#    next unless $i % 2;
    # Output a row.
    printf '%*s ', $width, is_prime($i) ? $i : '.';
    # End a row if we are on the last column.
    print "\n" unless $i % $spokes;
}
